Updated Many parts of The Docs
Games-With-Gabe-Community/Azurite-Docs pull request #3
Opened 2021-05-29 05:00 UTC by Pricter

2021-05-29 17:15 UTC, athaun requested changes
Please take a look at my comments, some of the changes look good and some are a little unecessary. I am doing this review on my phone, so if I missed something, please lmk through discord or reply to this message.

2021-05-29 17:15 UTC, athaun commented on tutorials/custom-renderer.html
> +                    If you have any questions, ping anybody from Helper role in the Games-With-Gabe discord.
This is set to voxelrifts because he is the author of the batch rendering API, he understands it best.

2021-05-29 17:15 UTC, athaun commented on docs/AABB.html
> -                <pre class="syntax-java">
We want to keep this pre tag, we will add a code sample at some point

2021-05-29 17:15 UTC, athaun commented on docs/Events.html
> -                    <tr><td><div class="danger"><strong>[SCRAPER:WARNING]</strong> The JavaDoc Scraper was unable to find the any data for the methods table. Please manually add any missing data or r
This is good, we do want to remove these scraper warnings

2021-05-29 17:15 UTC, athaun commented on docs/Events.html
> -                </pre>
Similar to my comment in AABB, we want to keep the pre tags

2021-05-30 01:03 UTC, athaun approved these changes

2021-05-30 01:44 UTC, Pricter commented
Ok I will change it

On Sun, May 30, 2021, 6:33 AM Asher ***@***.***> wrote:

> ***@***.**** approved this pull request.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/Games-With-Gabe-Community/Azurite-Docs/pull/3#pullrequestreview-671782613>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AQCVQ7EMHISJQXFYJR76F2DTQGFGXANCNFSM45X5BBEA>
> .
>

2023-10-05 11:47 UTC, closed without merging